### ISSUE TITLE
Complement of a label?

### ISSUE THREAD

**Issue by aubertc** [peterbro1/RCCS_Impl#10]
What is the syntax to indicate the complement of an action, i.e. "out a"?

I [thought it was 'a](https://github.com/peterbro1/RCCS_Impl/blob/e85bc9456105f249adf8f2484b0ab2df207882d9/src/main/java/me/gmx/parser/CCSGrammar.java#L19), but I get an error:

```
java -jar RCCS-1.0-SNAPSHOT.jar "a.P | 'a.Q" 
Create a.P
Walking... Memory: a
Walking... Memory: a.
Adding a. to prefixes
Walking... Memory: P
Create Q
Walking... Memory: Q
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "me.gmx.process.process.Process.origin()" because "o" is null
        at me.gmx.process.ProcessTemplate.prettyString(ProcessTemplate.java:67)
        at me.gmx.RCCS.main(RCCS.java:37)
```

**Comment by peterbro1** [comment]
Fixed
