### ISSUE TITLE
Making processes aliases for null operator

### ISSUE THREAD

**Issue by aubertc** [peterbro1/RCCS_Impl#9]
This is probably connected to [this issue](https://github.com/peterbro1/RCCS_Impl/issues/6): as of now, parsing a simple process causes an exception.

```
java -jar RCCS-1.0-SNAPSHOT.jar "P"
Create P
Walking... Memory: P
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "me.gmx.process.process.Process.origin()" because "o" is null
        at me.gmx.process.ProcessTemplate.prettyString(ProcessTemplate.java:67)
        at me.gmx.RCCS.main(RCCS.java:37)
```

A process "P" should be parsed as "0", and not cause any exception.

**Comment by aubertc** [comment]
Cf. https://github.com/peterbro1/RCCS_Impl/commit/5d596329eee439f9e710aee884ccf679ef34cfd5#r68487236

**Comment by aubertc** [comment]
The error now changed :-)

```
java -jar target/RCCS-1.0-SNAPSHOT.jar "P"

Begin matching with memory P

Found match!: P INDEX: ACTIONPREFIX_COMPLETE
Parsing into action prefix...
Creating prefix P
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "me.gmx.process.process.Process.origin()" because "o" is null
        at me.gmx.process.ProcessTemplate.prettyString(ProcessTemplate.java:62)
        at me.gmx.RCCS.main(RCCS.java:32)
```

**Comment by peterbro1** [comment]
Fixed
